AUTOMAKE_OPTIONS=no-dependencies

sysconf_DATA = \
datatypes.conf.sample \
inteltypes.conf.sample \
ntlv_types.conf.sample \
nuggets.conf.sample \
nuggettypes.conf.sample \
rzb.conf.sample \
rzb_logging.conf.sample

EXTRA_DIST = \
datatypes.conf.sample \
inteltypes.conf.sample \
magic \
Makefile.am \
ntlv_types.conf.sample \
nuggets.conf.sample \
nuggettypes.conf.sample \
rzb.conf.sample.in \
rzb_log.conf.simple.in

