# Copyright (c) 2011-2026 Cisco Systems, Inc.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

AUTOMAKE_OPTIONS = no-dependencies

razorbackschemadir = $(datadir)/razorback
razorbackschema_DATA = \
README.md \
block-id.schema.json \
block.schema.json \
event-id.schema.json \
event.schema.json \
hash.schema.json \
judgment.schema.json \
message-alert-child.schema.json \
message-alert-primary.schema.json \
message-block-submit.schema.json \
message-bye.schema.json \
message-cache-clear.schema.json \
message-cache-req.schema.json \
message-cache-resp.schema.json \
message-config-ack.schema.json \
message-config-error.schema.json \
message-config-update.schema.json \
message-empty.schema.json \
message-error.schema.json \
message-go.schema.json \
message-hello.schema.json \
message-inspection.schema.json \
message-judgment.schema.json \
message-log.schema.json \
message-output-event.schema.json \
message-output-inspection.schema.json \
message-output-log.schema.json \
message-pause.schema.json \
message-paused.schema.json \
message-reg-error.schema.json \
message-reg-req.schema.json \
message-reg-resp.schema.json \
message-rereg.schema.json \
message-running.schema.json \
message-term.schema.json \
ntlv-item.schema.json \
ntlv-list.schema.json \
nugget.schema.json \
string-list.schema.json \
uint8-list.schema.json \
uuid-list-entry.schema.json \
uuid-list.schema.json \
uuid.schema.json

EXTRA_DIST = $(razorbackschema_DATA)
