# Copyright (c) 2011-2026 Cisco Systems, Inc.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

AUTOMAKE_OPTIONS=no-dependencies

nobase_include_HEADERS = \
razorback/api.h \
razorback/block.h \
razorback/block_id.h \
razorback/block_pool.h \
razorback/config_next.h \
razorback/config_file.h \
razorback/connected_entity.h \
razorback/daemon.h \
razorback/debug.h \
razorback/event.h \
razorback/file.h \
razorback/fileserver.h \
razorback.h \
razorback/hash.h \
razorback/health.h \
razorback/inspector_queue.h \
razorback/json_buffer.h \
razorback/judgment.h \
razorback/list.h \
razorback/lock.h \
razorback/log.h \
razorback/message_formats.h \
razorback/message_body.h \
razorback/messages_next.h \
razorback/messages.h \
razorback/metadata.h \
razorback/ntlv.h \
razorback/nugget.h \
razorback/queue.h \
razorback/queue_list.h \
razorback/response_queue.h \
razorback/runtime_next.h \
razorback/socket.h \
razorback/string_list.h \
razorback/submission.h \
razorback/telemetry.h \
razorback/thread.h \
razorback/thread_pool.h \
razorback/timer.h \
razorback/types.h \
razorback/uuids.h \
razorback/visibility.h
