AUTOMAKE_OPTIONS=no-dependencies

nobase_include_HEADERS = \
razorback.h \
razorback/alert_queue.h \
razorback/api.h \
razorback/binary_buffer.h \
razorback/block.h \
razorback/block_id.h \
razorback/block_pool.h \
razorback/cache.h \
razorback/command_queue.h \
razorback/config_file.h \
razorback/connected_entity.h \
razorback/daemon.h \
razorback/debug.h \
razorback/hash.h \
razorback/input_queue.h \
razorback/inspector_queue.h \
razorback/judgment_queue.h \
razorback/log.h \
razorback/messages.h \
razorback/ntlv.h \
razorback/queue.h \
razorback/queue_list.h \
razorback/request_queue.h \
razorback/response_queue.h \
razorback/socket.h \
razorback/thread.h \
razorback/types.h \
razorback/uuids.h \
razorback/visibility.h
